"use client";

import { useState } from "react";
import { FileText, Download, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ReportSummary } from "@/lib/types";
import jsPDF from "jspdf";

export function ReportCard({ report }: { report: ReportSummary }) {
  const [open, setOpen] = useState(false);

  const handleDownload = () => {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const margin = 40;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - margin * 2;

    doc.setFontSize(16);
    doc.text(report.title, margin, 50);

    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(`Generated by ${report.generatedBy} · ${report.lastUpdated}`, margin, 68);

    doc.setFontSize(11);
    doc.setTextColor(20);
    const lines = doc.splitTextToSize(report.content, maxWidth);
    doc.text(lines, margin, 95);

    doc.save(`${report.title.replace(/\s+/g, "_")}.pdf`);
  };

  return (
    <>
      <div className="rounded-lg border border-border bg-surface p-5 shadow-soft flex items-start gap-4">
        <div className="h-9 w-9 rounded-md bg-primary/10 flex items-center justify-center shrink-0">
          <FileText className="h-4 w-4 text-primary" />
        </div>
        <div className="flex-1">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-ink">{report.title}</h3>
            <span className="text-xs text-ink-muted">{report.lastUpdated}</span>
          </div>
          <p className="mt-1 text-sm text-ink-muted leading-relaxed">{report.summary}</p>
          <p className="mt-2 text-xs text-ink-muted">Generated by {report.generatedBy}</p>
          <div className="mt-3 flex gap-2">
            <Button size="sm" variant="secondary" onClick={() => setOpen(true)}>
              Preview
            </Button>
            <Button size="sm" variant="ghost" onClick={handleDownload}>
              <Download className="h-3.5 w-3.5" />
              Download
            </Button>
          </div>
        </div>
      </div>

      {open && (
        <div
          className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-6"
          onClick={() => setOpen(false)}
        >
          <div
            className="bg-surface w-full max-w-3xl max-h-[85vh] rounded-lg shadow-xl overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-6 py-4 border-b border-border">
              <div>
                <h2 className="text-base font-semibold text-ink">{report.title}</h2>
                <p className="text-xs text-ink-muted mt-0.5">
                  {report.generatedBy} · {report.lastUpdated}
                </p>
              </div>
              <button onClick={() => setOpen(false)} className="text-ink-muted hover:text-ink">
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="px-6 py-5 overflow-y-auto text-sm text-ink leading-relaxed whitespace-pre-wrap">
              {report.content}
            </div>
            <div className="px-6 py-4 border-t border-border flex justify-end gap-2">
              <Button size="sm" variant="ghost" onClick={() => setOpen(false)}>
                Close
              </Button>
              <Button size="sm" onClick={handleDownload}>
                <Download className="h-3.5 w-3.5" />
                Download PDF
              </Button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}