INDUSTRY_TAGS = [
    "Food & Beverage",
    "Retail",
    "Groceries",
    "Textile & Apparel",
    "Electronics",
    "Pharmaceuticals",
    "FMCG",
    "Automotive Parts",
    "Home Appliances",
    "Furniture",
    "Cosmetics & Personal Care",
    "Hardware & Tools",
    "Sporting Goods",
    "Toys",
    "Stationery",
    "Jewelry",
    "Footwear",
    "Bakery",
    "Dairy",
    "Meat & Seafood",
    "Frozen Foods",
    "Beverages",
    "Confectionery",
    "Agricultural Products",
    "Construction Materials",
    "Industrial Equipment",
    "Electricals",
    "Plumbing Supplies",
    "Paints & Coatings",
    "Books & Media",
    "Pet Supplies",
    "Baby Products",
    "Health & Wellness",
    "Organic Foods",
    "Packaged Foods",
    "Spices & Condiments",
    "Tea & Coffee",
    "Alcohol & Spirits",
    "Office Supplies",
    "Luggage & Bags",
    "Watches & Accessories",
    "Eyewear",
    "Beauty & Skincare",
    "Fitness Equipment",
    "Outdoor & Camping",
    "Auto Accessories",
    "Tires",
    "Lubricants & Fluids",
    "Batteries",
    "Consumer Electronics",
    "Mobile Accessories",
    "Computer Hardware",
    "Software & IT Products",
    "Telecom Equipment",
    "Medical Devices",
    "Lab Supplies",
    "Chemicals",
    "Fertilizers",
    "Seeds & Agri-inputs",
    "Dairy Equipment",
    "Poultry",
    "Livestock Feed",
    "Textile Machinery",
    "Yarn & Fabric",
    "Leather Goods",
    "Kitchenware",
    "Cookware",
    "Home Decor",
    "Lighting",
    "Bedding & Linens",
    "Cleaning Supplies",
    "Laundry Products",
    "Personal Hygiene",
    "Diapers & Baby Care",
    "Educational Supplies",
    "Musical Instruments",
    "Party Supplies",
    "Gift Items",
    "Craft Supplies",
    "Gardening Supplies",
    "Pool & Spa Supplies",
    "Security Equipment",
    "Fire Safety Equipment",
    "Packaging Materials",
    "Logistics Equipment",
    "Warehouse Equipment",
    "Retail Fixtures",
    "POS Systems",
    "E-commerce Fulfillment",
    "Cold Chain / Refrigeration",
    "Bulk Commodities",
    "Specialty Foods",
    "Vegan/Plant-Based Products",
    "Gluten-Free Products",
    "Imported Goods",
    "Wholesale Distribution",
    "Duty-Free Retail",
    "Pharmacy Retail",
    "Convenience Store",
    "Supermarket Chain",
    "Department Store",
    "Hypermarket",
]
